server:
  port: 3034
  base-url: /notas
  session-store: memory
db:
  motor: postgresql
  host: localhost
  database: notas_db
  schema: notas
  user: notas_user
  password: sdfw234dsrge
  search_path: 
  - notas
install:
  dump:
    db:
      owner: notas_owner
    x-admin-can-create-tables: true
    enances: inline
    skip-content: true
    scripts:
      post-adapt: 
      - event_control_creates.sql
      - para-install.sql
      - ../node_modules/varcal/install/wrappers.sql
      - ../node_modules/pg-triggers/lib/recreate-his.sql
      - ../node_modules/pg-triggers/lib/table-changes.sql
      - ../node_modules/pg-triggers/lib/function-changes-trg.sql
      - ../node_modules/pg-triggers/lib/enance.sql
login:
  table: usuarios
  userFieldName: usuario
  passFieldName: clave
  rolFieldName: rol
  infoFieldList: [usuario, rol]
  activeClausule: activo_hasta
  plus:
    maxAge-5-sec: 5000    
    maxAge: 864000000
    maxAge-10-day: 864000000
    allowHttpLogin: true
    fileStore: false
    secret: secret some in blah blah
    skipCheckAlreadyLoggedIn: true
    loginForm:
      formTitle: Notas
      usernameLabel: usuario
      passwordLabel: clave
      buttonLabel: entrar
      formImg: img/login-lock-icon.png
    chPassForm:
      usernameLabel: usuario
      oldPasswordLabel: clave anterior
      newPasswordLabel: nueva clave
      repPasswordLabel: repetir nueva clave
      buttonLabel: Cambiar
      formTitle: Cambio de clave
  messages:
    userOrPassFail: el nombre de usuario no existe o la clave no corresponde
    lockedFail: el usuario se encuentra bloqueado
    inactiveFail: es usuario está marcado como inactivo
client-setup:
  cursors: true
  lang: es
  menu: true